const player1 = "Markus";
const player2 = "Theresa";

const quotes = [
  "Kein Bier. Keine Ausreden.",
  "Legenden trinken später.",
  "Der erste Schluck wird legendär.",
  "Heute wieder gewonnen.",
  "Disziplin schlägt Durst.",
  "Bier läuft nicht weg.",
  "Der Hopfen wartet geduldig.",
  "Ein kaltes Bier ist gut. Ein verdientes Bier ist besser.",
  "Vorfreude ist der beste Geschmacksverstärker.",
  "Heute gewinnt das Wasserglas.",
  "Der Kühlschrank wirkt etwas irritiert.",
  "Die Brauereien müssen jetzt stark sein.",
  "Der Durst darf reden. Entscheiden tut ihr.",
  "Noch nicht. Genau das ist der Punkt.",
  "Das Ziel riecht schon nach Lagerfeuer.",
  "Heute kein Bier. Heute Charakter.",
  "Prost später.",
  "Hopfenpause mit Haltung.",
  "Das Bier wird nicht schlechter. Nur verdienter.",
  "Kleine Entscheidung. Großer Sieg.",
  "Heute zählt. Morgen auch.",
  "Der Countdown macht keine Ausnahmen.",
  "Der Grill wartet schon.",
  "Wasser ist heute der heimliche Champion.",
  "Nicht jeder Sieg braucht Applaus.",
  "Der Feierabend bleibt. Das Bier wartet.",
  "Wer jetzt durchhält, erzählt später besser.",
  "Aus Verzicht wird Vorfreude.",
  "Heute wieder ein kleines Finale.",
  "Bald wird aus Geduld Geschmack.",
  "Die beste Zutat heißt Durchhalten.",
  "Bier kann warten. Geschichten nicht.",
  "Ein Tag ohne Bier ist ein Tag näher am Festival.",
  "Heute wird nicht diskutiert. Heute wird durchgezogen.",
  "Der erste Schluck bekommt gerade seine Vorgeschichte.",
  "Manchmal ist Nein sagen der beste Plan.",
  "Nicht schwach werden. Stark bleiben.",
  "Heute gewinnt nicht der Durst.",
  "Der Juli hat Regeln.",
  "Bierpause ist auch eine Kunstform.",
  "Durchhalten ist leiser als Angeben, aber stärker.",
  "Das Festivalbier wird mit jedem Tag legendärer.",
  "Wer warten kann, gewinnt den besseren Schluck.",
  "Heute ist kein Rückfalltag.",
  "Der Hopfen macht Urlaub.",
  "Die Challenge läuft. Ihr auch.",
  "Noch ein Tag für die Legende.",
  "Das Ziel bleibt größer als der Durst.",
  "Geduld ist flüssige Vorfreude.",
  "Alkoholfrei im Kopf. Festival im Blick.",
  "Heute wird Charakter gekühlt serviert.",
  "Der Kühlschrank muss da jetzt durch.",
  "Kein Bier ist auch eine Ansage.",
  "Jeder Tag macht den Moment größer.",
  "Der erste Schluck wird Applaus bekommen.",
  "Das Wasserglas hat heute Hauptrolle.",
  "Hopfen vermisst euch. Aber er versteht es.",
  "Ein Bier weniger. Eine Geschichte mehr.",
  "Der Countdown ist euer Trainingspartner.",
  "Heute wird nicht geschwächelt.",
  "Der Durst ist laut. Das Ziel ist lauter.",
  "Das Lagerfeuer wartet auf Gewinner.",
  "Heute bleibt der Kronkorken zu.",
  "Ihr seid näher dran als gestern.",
  "Das Bier steht nicht auf der Flucht.",
  "Vorfreude schlägt Gewohnheit.",
  "Heute ist ein guter Tag zum Durchhalten.",
  "Noch ein Nein. Noch ein Sieg.",
  "Stark bleiben. Später schmeckt es besser.",
  "Der Juli testet. Ihr antwortet.",
  "Das erste Bier soll sich lohnen.",
  "Kein Bier heute. Mehr Legende morgen.",
  "Bald knistert nicht nur das Feuer.",
  "Disziplin schmeckt später besser.",
  "Das Bier wird am Festival persönlich abgeholt.",
  "Heute kein Hopfen. Heute Fokus.",
  "Nur weil es kalt ist, muss man es nicht trinken.",
  "Der Durst hat kein Stimmrecht.",
  "Das Ziel ist offiziell wichtiger.",
  "Wieder ein Tag, den ihr abhaken könnt.",
  "Bierpause mit Stil.",
  "Die Challenge ist stärker als der Reflex.",
  "Heute bleibt der Bieröffner arbeitslos.",
  "Der erste Schluck trainiert gerade seinen Auftritt.",
  "Noch nicht. Aber bald.",
  "Festivalbier ist kein Alltagsbier.",
  "Ihr macht das nicht umsonst.",
  "Ein Monat Disziplin. Ein Moment Belohnung.",
  "Der Weg zum ersten Bier ist gepflastert mit Wasser.",
  "Der Hopfen wird euch wiedersehen.",
  "Das hier ist keine Pause. Das ist Vorbereitung.",
  "Heute zählt Haltung.",
  "Der Bierdurst darf im Wartezimmer Platz nehmen.",
  "Weniger Bier. Mehr Vorfreude.",
  "Jeder Tag ohne Bier macht den 31. größer.",
  "Die Zielgerade wird jeden Tag kürzer.",
  "Heute seid ihr eurem Festival-Ich näher.",
  "Kein Bier. Kein Drama.",
  "Wasser rein. Legende raus.",
  "Der Geschmack von Durchhalten kommt später.",
  "Die Challenge schreibt mit.",
  "Heute wird nicht angestoßen. Heute wird aufgebaut.",
  "Geduld ist der neue Hopfen.",
  "Das erste Bier verdient Publikum.",
  "Noch ein Tag für die Statistik.",
  "Bier kann jeder. Warten können Legenden.",
  "Die Kühlung läuft. Ihr wartet.",
  "Heute bleibt’s trocken. Im besten Sinn.",
  "Der Moment kommt. Nur nicht heute.",
  "Ein Bier am falschen Tag ist nur ein Getränk. Ein Bier am Ziel ist ein Ereignis.",

  "{player1}, bitte keine Verhandlungen mit dem Feierabendbier.",
  "{player2}, heute gewinnt wieder dein Zukunfts-Ich.",
  "{player1} und {player2}: Zwei Menschen. Ein Ziel. Kein Bier.",
  "Gerüchten zufolge träumt {player1} inzwischen von Hopfen.",
  "{player2} wurde zuletzt mit einem Wasserglas gesehen. Vorbildlich.",
  "Die Brauereien melden Nervosität. Verdächtigt werden {player1} und {player2}.",
  "{player1}, das Bier im Kühlschrank hat gefragt, ob du umgezogen bist.",
  "{player2}, das Festivalbier sammelt bereits Charakterpunkte.",
  "{player1} und {player2} machen aus Durst gerade Disziplin.",
  "Breaking News: {player1} und {player2} trotzen dem Feierabendbier.",
  "{player1}, heute keine spontane Qualitätskontrolle im Kühlschrank.",
  "{player2}, der Hopfen wartet höflich.",
  "{player1} und {player2} wurden zuletzt in Begleitung von Wasser gesichtet.",
  "{player1}, dein Bier hat Geduld. Du auch.",
  "{player2}, das erste Festivalbier merkt sich diesen Einsatz.",
  "{player1} und {player2}: offiziell im Team 'Später Prost'."
];
